# Generated by Django 5.2.3 on 2025-07-03 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionaries", "0003_alter_service_code_alter_service_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Трек-номер",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Объем (м³)",
                    ),
                ),
                (
                    "distance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Дистанция (км)"
                    ),
                ),
                (
                    "address_recipient",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Адрес получателя",
                    ),
                ),
                (
                    "address_from",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Адрес отправки",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечания"),
                ),
                (
                    "cargo_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="dictionaries.typecargo",
                        verbose_name="Тип груза",
                    ),
                ),
                (
                    "packaging_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="dictionaries.typepackaging",
                        verbose_name="Тип упаковки",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="dictionaries.service",
                        verbose_name="Сервис доставки",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="dictionaries.statusdelivery",
                        verbose_name="Статус доставки",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="dictionaries.transport",
                        verbose_name="Транспорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tracking_number"],
                        name="delivery_de_trackin_de682d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="delivery_de_status__dbe673_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="delivery_de_created_8e100d_idx"
                    ),
                ],
            },
        ),
    ]
